### PR TITLE
Lambda support

### PR DESCRIPTION
**Pull request by adambaratz**

### CODE REVIEW

**Comment by jbboehr** [comment]
PHP5 looks good, but valgrind is giving a bunch of errors on PHP7 (see attached)













[MustacheLambdaHelper__render-closure.mem.txt](https://github.com/jbboehr/php-mustache/files/18057/MustacheLambdaHelper__render-closure.mem.txt)
[MustacheLambdaHelper__render-object.mem.txt](https://github.com/jbboehr/php-mustache/files/18054/MustacheLambdaHelper__render-object.mem.txt)
[Mustache__render-lambda-closure-section.mem.txt](https://github.com/jbboehr/php-mustache/files/18058/Mustache__render-lambda-closure-section.mem.txt)
[Mustache__render-lambda-closure-variable.mem.txt](https://github.com/jbboehr/php-mustache/files/18053/Mustache__render-lambda-closure-variable.mem.txt)
[Mustache__render-lambda-object-method.mem.txt](https://github.com/jbboehr/php-mustache/files/18056/Mustache__render-lambda-object-method.mem.txt)
[mustache-spec-~lambdas-escaping.mem.txt](https://github.com/jbboehr/php-mustache/files/18055/mustache-spec-.lambdas-escaping.mem.txt)
[mustache-spec-~lambdas-interpolation.mem.txt](https://github.com/jbboehr/php-mustache/files/18059/mustache-spec-.lambdas-interpolation.mem.txt)
[mustache-spec-~lambdas-interpolation-alternate-delimiters.mem.txt](https://github.com/jbboehr/php-mustache/files/18061/mustache-spec-.lambdas-interpolation-alternate-delimiters.mem.txt)
[mustache-spec-~lambdas-interpolation-expansion.mem.txt](https://github.com/jbboehr/php-mustache/files/18060/mustache-spec-.lambdas-interpolation-expansion.mem.txt)
[mustache-spec-~lambdas-interpolation-multiple-calls.mem.txt](https://github.com/jbboehr/php-mustache/files/18064/mustache-spec-.lambdas-interpolation-multiple-calls.mem.txt)
[mustache-spec-~lambdas-section.mem.txt](https://github.com/jbboehr/php-mustache/files/18063/mustache-spec-.lambdas-section.mem.txt)
[mustache-spec-~lambdas-section-alternate-delimiters.mem.txt](https://github.com/jbboehr/php-mustache/files/18062/mustache-spec-.lambdas-section-alternate-delimiters.mem.txt)
[mustache-spec-~lambdas-section-expansion.mem.txt](https://github.com/jbboehr/php-mustache/files/18066/mustache-spec-.lambdas-section-expansion.mem.txt)
[mustache-spec-~lambdas-section-multiple-calls.mem.txt](https://github.com/jbboehr/php-mustache/files/18065/mustache-spec-.lambdas-section-multiple-calls.mem.txt)

**Comment by jbboehr** [comment]
And two segfaults w/o valgrind
[Mustache__render-lambda-closure-section.diff.txt](https://github.com/jbboehr/php-mustache/files/18071/Mustache__render-lambda-closure-section.diff.txt)
[Mustache__render-lambda-closure-section.out.txt](https://github.com/jbboehr/php-mustache/files/18073/Mustache__render-lambda-closure-section.out.txt)
[mustache-spec-~lambdas-section-alternate-delimiters.diff.txt](https://github.com/jbboehr/php-mustache/files/18074/mustache-spec-.lambdas-section-alternate-delimiters.diff.txt)
[mustache-spec-~lambdas-section-alternate-delimiters.out.txt](https://github.com/jbboehr/php-mustache/files/18072/mustache-spec-.lambdas-section-alternate-delimiters.out.txt)

**Comment by jbboehr** [comment]
If I have some time, I'll try to take a look at it.

**Comment by adambaratz** [comment]
I was able to address all but one of the valgrind issues. The one associated with tests/MustacheCode__toReadableString.phpt appears without my changes applied.

I wasn't able to reproduce the segfaults in my dev environment. Travis CI doesn't report them either. I wonder if they'll go away after applying my latest commit.

**Comment by jbboehr** [comment]
Yep, looks good!

**Pull request merged**
